// src/components/ShipModal.vue
<template>
  <div class="modal" v-if="isOpen">
    <div class="modal-content">
      <span class="close" @click="closeModal">&times;</span>
      <h3>{{ ship.MMSI }}</h3>
      <p>Type: {{ ship.VesselType }}</p>
      <p>Latitude: {{ ship.latitude }}</p>
      <p>Longitude: {{ ship.longitude }}</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'ShipModal',
  props: {
    ship: {
      type: Object,
      required: true
    },
    isOpen: {
      type: Boolean,
      required: true
    },
    closeModal: {
      type: Function,
      required: true
    }
  }
});
</script>

<style scoped>
.modal {
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: rgba(0, 0, 0, 0.4);
}

.modal-content {
  background-color: #fefefe;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
  max-width: 500px;
  border-radius: 8px;
}

.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}
</style>

// src/components/shipModal.tsx
// import refactored data fetch (vessel) and react
import { Vessel } from './Vessel';
import React from 'react';



interface ShipModalProps {
    vessel ?:  Vessel;
    isOpen: boolean;
    closeModal: () => void;
}



const ShipModal: React.FC<ShipModalProps> = ({ vessel, isOpen, closeModal }) => {
    if (!isOpen) return null;

    return (
        <div className="flex justify-center items-center fixed z-10 left-0 top-0 w-full h-full overflow-auto bg-black bg-opacity-40">
            <div className="bg-white p-5 border border-gray-400 w-4/5 max-w-lg rounded-lg">
                <span className="text-gray-500 float-right text-2xl font-bold cursor-pointer hover:text-black" onClick={closeModal}>&times;</span>
                {vessel && (
                    <>
                        <h3>{vessel.MMSI}</h3>
                        <p>Type: {vessel.VesselType}</p>
                        <p>Latitude: {vessel.latitude}</p>
                        <p>Longitude: {vessel.longitude}</p>
                    </>
                )}
            </div>
        </div>
    );
};

export default ShipModal;
