// src/components/ShipCard.tsx
// import refactored data fetch (vessel)

/* function ShipCard({ ship }) {
    return (
        <div className="border border-gray-300 p-4 m-2 rounded-lg shadow-md">
            <h3>{ship.MMSI}</h3>
            <p>Type: {ship.VesselType}</p>
            <p>Latitude: {ship.latitude}</p>
            <p>Longitude: {ship.longitude}</p>
            <p>COG: {ship.cog}</p>
            <p>SOG: {ship.sog}</p>
        </div>
    );
} */

// src/components/ShipCard.vue
<template>
  <div class="ship-card">
    <h3>{{ ship.MMSI }}</h3>
    <p>Type: {{ ship.VesselType }}</p>
    <p>Latitude: {{ ship.latitude }}</p>
    <p>Longitude: {{ ship.longitude }}</p>
    <p>COG: {{ ship.cog }}</p>
    <p>SOG: {{ ship.sog }}</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ShipCard',
  props: {
    ship: {
      type: Object,
      required: true
    },
    
  }
});
</script>

<style scoped>
.ship-card {
  border: 1px solid #ccc;
  padding: 16px;
  margin: 8px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}
</style>
